-- liquibase formatted sql

-- changeset Homychok:1
CREATE TABLE bid (
                         bidder_id  BIGINT PRIMARY KEY,
                         bidder_name VARCHAR(255) NOT NULL,
                         bidder_date TIMESTAMP NOT NULL,
                         lot_id      BIGINT NOT NULL,
                         lot_last_bid  INTEGER REFERENCES lot(lot_last_bid)
);

ALTER TABLE bid ALTER COLUMN bidder_id ADD GENERATED BY DEFAULT AS IDENTITY;