-- liquibase formatted sql

-- changeset Homychok:1
CREATE TABLE bid (
                     lot_id      BIGINT NOT NULL,
                     lot_status  VARCHAR(255) NOT NULL,
                     lot_title VARCHAR(255) NOT NULL,
                     lot_description VARCHAR(255) NOT NULL,
                     lot_current_price INTEGER NOT NULL,
                     lot_last_bid  INTEGER PRIMARY KEY
);

ALTER TABLE lot ALTER COLUMN lot_id ADD GENERATED BY DEFAULT AS IDENTITY;